# CI application and infrastructure configuration
spring:
  profiles:
    active: native
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# CI service discovery configuration
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false